// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/joaochiroli/projeto-otel-na-pratica/construido-seu-collector

go 1.24

require (
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.134.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.134.0
	go.opentelemetry.io/collector/component v1.40.0
	go.opentelemetry.io/collector/confmap v1.40.0
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.40.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.40.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.40.0
	go.opentelemetry.io/collector/connector v0.134.0
	go.opentelemetry.io/collector/connector/forwardconnector v0.134.0
	go.opentelemetry.io/collector/exporter v0.134.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.134.0
	go.opentelemetry.io/collector/exporter/nopexporter v0.134.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.134.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.134.0
	go.opentelemetry.io/collector/extension v1.40.0
	go.opentelemetry.io/collector/otelcol v0.134.0
	go.opentelemetry.io/collector/processor v1.40.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.134.0
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.134.0
	go.opentelemetry.io/collector/receiver v1.40.0
	go.opentelemetry.io/collector/receiver/nopreceiver v0.134.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.134.0
	golang.org/x/sys v0.35.0
)

require (
	cloud.google.com/go/compute/metadata v0.7.0 // indirect
	github.com/GehirnInc/crypt v0.0.0-20230320061759-8cc1b52080c5 // indirect
	github.com/IBM/sarama v1.46.0 // indirect
	github.com/alecthomas/participle/v2 v2.1.4 // indirect
	github.com/antchfx/xmlquery v1.4.4 // indirect
	github.com/antchfx/xpath v1.3.5 // indirect
	github.com/apache/thrift v0.22.0 // indirect
	github.com/aws/aws-msk-iam-sasl-signer-go v1.0.4 // indirect
	github.com/aws/aws-sdk-go-v2 v1.36.4 // indirect
	github.com/aws/aws-sdk-go-v2/config v1.29.16 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.17.69 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.16.31 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.35 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.35 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.8.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.12.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.12.16 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.25.4 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.30.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.33.21 // indirect
	github.com/aws/smithy-go v1.22.2 // indirect
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/cenkalti/backoff/v5 v5.0.3 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/coreos/go-oidc/v3 v3.15.0 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/eapache/go-resiliency v1.7.0 // indirect
	github.com/eapache/go-xerial-snappy v0.0.0-20230731223053-c322873962e3 // indirect
	github.com/eapache/queue v1.1.0 // indirect
	github.com/ebitengine/purego v0.8.4 // indirect
	github.com/elastic/go-grok v0.3.1 // indirect
	github.com/elastic/lunes v0.1.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/foxboron/go-tpm-keyfiles v0.0.0-20250323135004-b31fac66206e // indirect
	github.com/fsnotify/fsnotify v1.9.0 // indirect
	github.com/go-jose/go-jose/v4 v4.1.2 // indirect
	github.com/go-logr/logr v1.4.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/go-viper/mapstructure/v2 v2.4.0 // indirect
	github.com/gobwas/glob v0.2.3 // indirect
	github.com/goccy/go-json v0.10.5 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/golang/snappy v1.0.0 // indirect
	github.com/google/go-tpm v0.9.5 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.27.1 // indirect
	github.com/hashicorp/go-uuid v1.0.3 // indirect
	github.com/hashicorp/go-version v1.7.0 // indirect
	github.com/hashicorp/golang-lru v0.5.4 // indirect
	github.com/hashicorp/golang-lru/v2 v2.0.7 // indirect
	github.com/iancoleman/strcase v0.3.0 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/jaegertracing/jaeger-idl v0.6.0 // indirect
	github.com/jcmturner/aescts/v2 v2.0.0 // indirect
	github.com/jcmturner/dnsutils/v2 v2.0.0 // indirect
	github.com/jcmturner/gofork v1.7.6 // indirect
	github.com/jcmturner/gokrb5/v8 v8.4.4 // indirect
	github.com/jcmturner/rpc/v2 v2.0.3 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/klauspost/compress v1.18.0 // indirect
	github.com/knadh/koanf/maps v0.1.2 // indirect
	github.com/knadh/koanf/providers/confmap v1.0.0 // indirect
	github.com/knadh/koanf/v2 v2.2.2 // indirect
	github.com/lightstep/go-expohisto v1.0.0 // indirect
	github.com/lufia/plan9stats v0.0.0-20211012122336-39d0f177ccd0 // indirect
	github.com/magefile/mage v1.15.0 // indirect
	github.com/mitchellh/copystructure v1.2.0 // indirect
	github.com/mitchellh/reflectwalk v1.0.2 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.3-0.20250322232337-35a7c28c31ee // indirect
	github.com/mostynb/go-grpc-compression v1.2.3 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/filter v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/kafka v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/pdatautil v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/batchpersignal v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/core/xidutils v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/kafka/configkafka v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/kafka/topic v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger v0.134.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/zipkin v0.134.0 // indirect
	github.com/openzipkin/zipkin-go v0.4.3 // indirect
	github.com/pierrec/lz4/v4 v4.1.22 // indirect
	github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 // indirect
	github.com/power-devops/perfstat v0.0.0-20210106213030-5aafc221ea8c // indirect
	github.com/prometheus/client_golang v1.22.0 // indirect
	github.com/prometheus/client_model v0.6.2 // indirect
	github.com/prometheus/common v0.65.0 // indirect
	github.com/prometheus/procfs v0.17.0 // indirect
	github.com/rcrowley/go-metrics v0.0.0-20250401214520-65e299d6c5c9 // indirect
	github.com/rs/cors v1.11.1 // indirect
	github.com/shirou/gopsutil/v4 v4.25.7 // indirect
	github.com/spf13/cobra v1.9.1 // indirect
	github.com/spf13/pflag v1.0.6 // indirect
	github.com/stretchr/testify v1.11.1 // indirect
	github.com/tg123/go-htpasswd v1.2.4 // indirect
	github.com/tklauser/go-sysconf v0.3.15 // indirect
	github.com/tklauser/numcpus v0.10.0 // indirect
	github.com/twmb/franz-go v1.19.5 // indirect
	github.com/twmb/franz-go/pkg/kmsg v1.11.2 // indirect
	github.com/twmb/franz-go/pkg/sasl/kerberos v1.1.0 // indirect
	github.com/twmb/franz-go/plugin/kzap v1.1.2 // indirect
	github.com/twmb/murmur3 v1.1.8 // indirect
	github.com/ua-parser/uap-go v0.0.0-20240611065828-3a4781585db6 // indirect
	github.com/xdg-go/pbkdf2 v1.0.0 // indirect
	github.com/xdg-go/scram v1.1.2 // indirect
	github.com/xdg-go/stringprep v1.0.4 // indirect
	github.com/yusufpapurcu/wmi v1.2.4 // indirect
	go.etcd.io/bbolt v1.4.3 // indirect
	go.opentelemetry.io/auto/sdk v1.1.0 // indirect
	go.opentelemetry.io/collector v0.134.0 // indirect
	go.opentelemetry.io/collector/client v1.40.0 // indirect
	go.opentelemetry.io/collector/component/componentstatus v0.134.0 // indirect
	go.opentelemetry.io/collector/component/componenttest v0.134.0 // indirect
	go.opentelemetry.io/collector/config/configauth v0.134.0 // indirect
	go.opentelemetry.io/collector/config/configcompression v1.40.0 // indirect
	go.opentelemetry.io/collector/config/configgrpc v0.134.0 // indirect
	go.opentelemetry.io/collector/config/confighttp v0.134.0 // indirect
	go.opentelemetry.io/collector/config/configmiddleware v0.134.0 // indirect
	go.opentelemetry.io/collector/config/confignet v1.40.0 // indirect
	go.opentelemetry.io/collector/config/configopaque v1.40.0 // indirect
	go.opentelemetry.io/collector/config/configoptional v0.134.0 // indirect
	go.opentelemetry.io/collector/config/configretry v1.40.0 // indirect
	go.opentelemetry.io/collector/config/configtelemetry v0.134.0 // indirect
	go.opentelemetry.io/collector/config/configtls v1.40.0 // indirect
	go.opentelemetry.io/collector/confmap/xconfmap v0.134.0 // indirect
	go.opentelemetry.io/collector/connector/connectortest v0.134.0 // indirect
	go.opentelemetry.io/collector/connector/xconnector v0.134.0 // indirect
	go.opentelemetry.io/collector/consumer v1.40.0 // indirect
	go.opentelemetry.io/collector/consumer/consumererror v0.134.0 // indirect
	go.opentelemetry.io/collector/consumer/consumererror/xconsumererror v0.134.0 // indirect
	go.opentelemetry.io/collector/consumer/consumertest v0.134.0 // indirect
	go.opentelemetry.io/collector/consumer/xconsumer v0.134.0 // indirect
	go.opentelemetry.io/collector/exporter/exporterhelper v0.134.0 // indirect
	go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper v0.134.0 // indirect
	go.opentelemetry.io/collector/exporter/exportertest v0.134.0 // indirect
	go.opentelemetry.io/collector/exporter/xexporter v0.134.0 // indirect
	go.opentelemetry.io/collector/extension/extensionauth v1.40.0 // indirect
	go.opentelemetry.io/collector/extension/extensioncapabilities v0.134.0 // indirect
	go.opentelemetry.io/collector/extension/extensionmiddleware v0.134.0 // indirect
	go.opentelemetry.io/collector/extension/extensiontest v0.134.0 // indirect
	go.opentelemetry.io/collector/extension/xextension v0.134.0 // indirect
	go.opentelemetry.io/collector/featuregate v1.40.0 // indirect
	go.opentelemetry.io/collector/internal/fanoutconsumer v0.134.0 // indirect
	go.opentelemetry.io/collector/internal/memorylimiter v0.134.0 // indirect
	go.opentelemetry.io/collector/internal/sharedcomponent v0.134.0 // indirect
	go.opentelemetry.io/collector/internal/telemetry v0.134.0 // indirect
	go.opentelemetry.io/collector/pdata v1.40.0 // indirect
	go.opentelemetry.io/collector/pdata/pprofile v0.134.0 // indirect
	go.opentelemetry.io/collector/pdata/testdata v0.134.0 // indirect
	go.opentelemetry.io/collector/pdata/xpdata v0.134.0 // indirect
	go.opentelemetry.io/collector/pipeline v1.40.0 // indirect
	go.opentelemetry.io/collector/pipeline/xpipeline v0.134.0 // indirect
	go.opentelemetry.io/collector/processor/processorhelper v0.134.0 // indirect
	go.opentelemetry.io/collector/processor/processorhelper/xprocessorhelper v0.134.0 // indirect
	go.opentelemetry.io/collector/processor/processortest v0.134.0 // indirect
	go.opentelemetry.io/collector/processor/xprocessor v0.134.0 // indirect
	go.opentelemetry.io/collector/receiver/receiverhelper v0.134.0 // indirect
	go.opentelemetry.io/collector/receiver/receivertest v0.134.0 // indirect
	go.opentelemetry.io/collector/receiver/xreceiver v0.134.0 // indirect
	go.opentelemetry.io/collector/service v0.134.0 // indirect
	go.opentelemetry.io/collector/service/hostcapabilities v0.134.0 // indirect
	go.opentelemetry.io/contrib/bridges/otelzap v0.12.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.62.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.62.0 // indirect
	go.opentelemetry.io/contrib/otelconf v0.16.0 // indirect
	go.opentelemetry.io/contrib/propagators/b3 v1.36.0 // indirect
	go.opentelemetry.io/otel v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.13.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/prometheus v0.58.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutlog v0.13.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v1.37.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.37.0 // indirect
	go.opentelemetry.io/otel/log v0.13.0 // indirect
	go.opentelemetry.io/otel/metric v1.37.0 // indirect
	go.opentelemetry.io/otel/sdk v1.37.0 // indirect
	go.opentelemetry.io/otel/sdk/log v0.13.0 // indirect
	go.opentelemetry.io/otel/sdk/metric v1.37.0 // indirect
	go.opentelemetry.io/otel/trace v1.37.0 // indirect
	go.opentelemetry.io/proto/otlp v1.7.0 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	go.uber.org/zap v1.27.0 // indirect
	go.yaml.in/yaml/v3 v3.0.4 // indirect
	golang.org/x/crypto v0.41.0 // indirect
	golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842 // indirect
	golang.org/x/net v0.43.0 // indirect
	golang.org/x/oauth2 v0.30.0 // indirect
	golang.org/x/text v0.28.0 // indirect
	gonum.org/v1/gonum v0.16.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20250707201910-8d1bb00bc6a7 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20250707201910-8d1bb00bc6a7 // indirect
	google.golang.org/grpc v1.75.0 // indirect
	google.golang.org/protobuf v1.36.8 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	sigs.k8s.io/yaml v1.5.0 // indirect
)

replace github.com/openshift/api => github.com/openshift/api v0.0.0-20230726162818-81f778f3b3ec

replace go.opentelemetry.io/otel/exporters/prometheus => go.opentelemetry.io/otel/exporters/prometheus v0.58.0
